import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <!--Animated Lower Thirds v1.6--> */}
      {/* <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Lower thirds Source</title>
    <link rel="stylesheet" href="../common/css/style-source.css" />
    <script src="../common/js/jquery.js"></script>
  </head> */}
      <body className="browser-source lower-thirds">
        {/* <!--Lower third 1--> */}
        <div id="lower-third-1" className="alt left style-1 hide-anim">
          <div id="alt-1-logo" className="logo no-logo">
            <img id="alt-1-logo-image" src="//:0" />
          </div>
          <div className="graph-1"></div>
          <div className="text-content">
            <div className="text-mask">
              <div id="alt-1-name"></div>
            </div>
            <div className="text-mask">
              <div id="alt-1-info"></div>
            </div>
          </div>
          <div className="graph-2"></div>
        </div>

        {/* <!--Lower third 2--> */}
        <div id="lower-third-2" className="alt left style-1 hide-anim">
          <div id="alt-2-logo" className="logo no-logo">
            <img id="alt-2-logo-image" src="//:0" />
          </div>
          <div className="graph-1"></div>
          <div className="text-content">
            <div className="text-mask">
              <div id="alt-2-name"></div>
            </div>
            <div className="text-mask">
              <div id="alt-2-info"></div>
            </div>
          </div>
          <div className="graph-2"></div>
        </div>

        {/* <!--Lower third 3--> */}
        <div id="lower-third-3" className="alt left style-1 hide-anim">
          <div id="alt-3-logo" className="logo no-logo">
            <img id="alt-3-logo-image" src="//:0" />
          </div>
          <div className="graph-1"></div>
          <div className="text-content">
            <div className="text-mask">
              <div id="alt-3-name"></div>
            </div>
            <div className="text-mask">
              <div id="alt-3-info"></div>
            </div>
          </div>
          <div className="graph-2"></div>
        </div>

        {/* <!--Lower third 4--> */}
        <div id="lower-third-4" className="alt left style-1 hide-anim">
          <div id="alt-4-logo" className="logo no-logo">
            <img id="alt-4-logo-image" src="//:0" />
          </div>
          <div className="graph-1"></div>
          <div className="text-content">
            <div className="text-mask">
              <div id="alt-4-name"></div>
            </div>
            <div className="text-mask">
              <div id="alt-4-info"></div>
            </div>
          </div>
          <div className="graph-2"></div>
        </div>

        {/* <script src="browser-source.js" type="text/javascript"></script> */}
      </body>
    </html>
  );
}
