import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body>
       */}
      <body className="lower-thirds-panel panel">
        <div
          id="alt-panel"
          className="static-panel-top"
          // style={"margin-bottom: 0px"}
        >
          <div id="sortable"></div>

          <div id="fileNames"></div>

          <div id="alt-preview" className="active">
            <label>
              <div className="icon icon-search"></div>
            </label>
            <div id="toggle-preview" className="active">
              <div className="icon icon-chevron-down"></div>
            </div>
            <div className="embed-container">{children}</div>
          </div>
        </div>

        {/* <script src="control-panel.js" type="text/javascript"></script> */}
      </body>
    </html>
  );
}
